services:
  db:
    image: postgres:15
    container_name: flowable-db
    platform: linux/arm64/v8   # Postgres je multi-arch, na Macu běží nativně
    environment:
      POSTGRES_DB: flowable
      POSTGRES_USER: flowable
      POSTGRES_PASSWORD: flowable
      TZ: Europe/Prague
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flowable -d flowable"]
      interval: 10s
      timeout: 5s
      retries: 10

  flowable-rest:
    image: flowable/flowable-rest:7.2.0
    container_name: flowable-rest
    platform: linux/amd64          # <<< emulace x86_64
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/flowable
      SPRING_DATASOURCE_USERNAME: flowable
      SPRING_DATASOURCE_PASSWORD: flowable
      SERVER_PORT: 8080
      TZ: Europe/Prague

      # Volitelné: vynucení REST uživatele (kdyby default nebyl vytvořen)
      FLOWABLE_REST_APP_ADMIN_USER_ID: rest-admin
      FLOWABLE_REST_APP_ADMIN_PASSWORD: test
      FLOWABLE_REST_APP_ADMIN_FIRST_NAME: Rest
      FLOWABLE_REST_APP_ADMIN_LAST_NAME: Admin
    ports:
      - "8090:8080"
    volumes:
      - ./addons:/additional-classpath:ro
    healthcheck:
      test:
        - CMD-SHELL
        - >
          wget -q --spider -T 5
          --header 'Authorization: Basic cmVzdC1hZG1pbjp0ZXN0'
          http://127.0.0.1:8080/flowable-rest/service/management/engine
          || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  deploy-process:
    image: curlimages/curl:latest
    container_name: flowable-deploy-process
    depends_on:
      flowable-rest:
        condition: service_healthy
    volumes:
      - ./srd-process.bpmn20.xml:/tmp/srd-process.bpmn20.xml:ro
    command: -v --fail --show-error -u rest-admin:test --form "file=@/tmp/srd-process.bpmn20.xml;type=application/xml" http://flowable-rest:8080/flowable-rest/service/repository/deployments
    restart: "no"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  flowable-http-worker:
    build: .
    image: flowable-http-worker:latest
    depends_on:
      deploy-process:
        condition: service_completed_successfully
    restart: unless-stopped
    environment:
      HTTP_LOG_API_PORT: 5005
    ports:
      - "5005:5005"
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          curl --fail --silent http://127.0.0.1:${HTTP_LOG_API_PORT:-5005}/health >/dev/null
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  dbdata:
